### ISSUE TITLE
error in main.dart

### ISSUE THREAD

**Issue by abhishek-joflee** [huynguyennovem/netshare#1]
https://github.com/huynguyennovem/netshare/blob/d6d9a6f1f901637c545602acc7506d2c4e93d2c9/lib/main.dart#L92

The named parameter 'iconButtonTheme' isn't defined.

Is this a test to see, that people are looking this project or not 😄 ?

**Comment by huynguyennovem** [comment]
Hi @abhishek-joflee 
Thanks for filing the issue. I forgot to note that this project is running on Flutter `beta` channel currently. So, please switch to the latest `beta` or `master` channel and retry.
